#confi para vincular db
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") %>
  username: <%= ENV.fetch("DATABASE_USERNAME") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") %>

test:
  <<: *default
  database: compufiis_test

production:
  <<: *default
  database: compufiis_production
